# Generated by Django 5.1.7 on 2025-06-04 19:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('alergias', models.TextField(blank=True, help_text='Liste as alergias conhecidas')),
                ('medicamentos_uso', models.TextField(blank=True, help_text='Medicamentos em uso contínuo')),
                ('condicoes_cronicas', models.TextField(blank=True, help_text='Condições crônicas conhecidas')),
                ('contato_emergencia_nome', models.CharField(blank=True, max_length=100)),
                ('contato_emergencia_telefone', models.CharField(blank=True, max_length=15)),
                ('plano_saude', models.CharField(blank=True, max_length=100)),
                ('numero_carteirinha', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('laboratorial', 'Laboratorial'), ('imagem', 'Imagem'), ('cardiologico', 'Cardiológico'), ('neurologico', 'Neurológico'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('preparo', models.TextField(blank=True, help_text='Instruções de preparo para o exame')),
                ('valor_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Exame',
                'verbose_name_plural': 'Tipos de Exames',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('biografia', models.TextField(blank=True)),
                ('formacao', models.TextField(blank=True)),
                ('experiencia_anos', models.PositiveIntegerField(default=0)),
                ('valor_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('especialidades', models.ManyToManyField(related_name='medicos', to='meu_app.especialidade')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField()),
                ('duracao_minutos', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('faltou', 'Paciente Faltou')], default='agendada', max_length=20)),
                ('tipo', models.CharField(choices=[('primeira_consulta', 'Primeira Consulta'), ('retorno', 'Retorno'), ('urgencia', 'Urgência'), ('rotina', 'Rotina')], default='primeira_consulta', max_length=20)),
                ('motivo', models.TextField(help_text='Motivo da consulta')),
                ('observacoes', models.TextField(blank=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='meu_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='meu_app.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('consulta_agendada', 'Consulta Agendada'), ('consulta_cancelada', 'Consulta Cancelada'), ('exame_disponivel', 'Exame Disponível'), ('lembrete_consulta', 'Lembrete de Consulta'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doencas_previas', models.TextField(blank=True)),
                ('cirurgias_previas', models.TextField(blank=True)),
                ('hospitalizacoes', models.TextField(blank=True)),
                ('vacinas', models.TextField(blank=True)),
                ('historia_familiar', models.TextField(blank=True)),
                ('habitos', models.TextField(blank=True, help_text='Tabagismo, etilismo, atividade física, etc.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_medico', to='meu_app.paciente')),
            ],
            options={
                'verbose_name': 'Histórico Médico',
                'verbose_name_plural': 'Históricos Médicos',
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField()),
                ('historia_doenca_atual', models.TextField()),
                ('historia_patologica_pregressa', models.TextField(blank=True)),
                ('historia_familiar', models.TextField(blank=True)),
                ('historia_social', models.TextField(blank=True)),
                ('medicamentos_uso', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('pressao_arterial', models.CharField(blank=True, max_length=20)),
                ('frequencia_cardiaca', models.CharField(blank=True, max_length=10)),
                ('temperatura', models.CharField(blank=True, max_length=10)),
                ('saturacao_oxigenio', models.CharField(blank=True, max_length=10)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('exame_geral', models.TextField(blank=True)),
                ('sistema_cardiovascular', models.TextField(blank=True)),
                ('sistema_respiratorio', models.TextField(blank=True)),
                ('sistema_digestivo', models.TextField(blank=True)),
                ('sistema_neurologico', models.TextField(blank=True)),
                ('outros_sistemas', models.TextField(blank=True)),
                ('diagnostico_principal', models.TextField()),
                ('diagnosticos_secundarios', models.TextField(blank=True)),
                ('cid10', models.CharField(blank=True, help_text='Código CID-10', max_length=10)),
                ('conduta', models.TextField()),
                ('prescricao', models.TextField(blank=True)),
                ('exames_solicitados', models.TextField(blank=True)),
                ('orientacoes', models.TextField(blank=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='meu_app.consulta')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicamentos', models.TextField(help_text='Lista de medicamentos prescritos')),
                ('posologia', models.TextField(help_text='Instruções de uso')),
                ('observacoes', models.TextField(blank=True)),
                ('validade', models.DateField(help_text='Data de validade da receita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='meu_app.consulta')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_agendamento', models.DateTimeField(blank=True, null=True)),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('local_realizacao', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('resultado', models.TextField(blank=True)),
                ('arquivo_resultado', models.FileField(blank=True, null=True, upload_to='exames/')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='meu_app.consulta')),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_solicitados', to='meu_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='meu_app.paciente')),
                ('tipo_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.tipoexame')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='meu_app.medico')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'unique_together': {('medico', 'data_hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='MedicoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculo', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_vinculados', to='meu_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos_vinculados', to='meu_app.paciente')),
            ],
            options={
                'verbose_name': 'Vínculo Médico-Paciente',
                'verbose_name_plural': 'Vínculos Médico-Paciente',
                'unique_together': {('medico', 'paciente')},
            },
        ),
    ]
