# Generated by Django 4.2.7 on 2025-08-25 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_especialidade_paciente_tipoexame_alter_user_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crm', models.CharField(max_length=20)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('instituicao_formacao', models.CharField(blank=True, max_length=150)),
                ('ano_formacao', models.CharField(blank=True, max_length=4)),
                ('residencia', models.CharField(blank=True, max_length=150)),
                ('instituicao_residencia', models.CharField(blank=True, max_length=150)),
                ('ano_residencia', models.CharField(blank=True, max_length=4)),
                ('experiencia', models.TextField(blank=True)),
                ('motivacao', models.TextField(blank=True)),
                ('diploma_medicina', models.FileField(blank=True, null=True, upload_to='solicitacoes/diplomas/')),
                ('certificado_residencia', models.FileField(blank=True, null=True, upload_to='solicitacoes/certificados/')),
                ('comprovante_experiencia', models.FileField(blank=True, null=True, upload_to='solicitacoes/experiencia/')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('fail', 'Falha')], default='success', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-created_at'],
            },
        ),
    ]
