# Generated by Django 4.2.7 on 2025-08-25 23:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0003_solicitacaomedico_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('apresentacao', models.CharField(blank=True, max_length=100)),
                ('concentracao', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'unique_together': {('nome', 'apresentacao', 'concentracao')},
            },
        ),
        migrations.RemoveField(
            model_name='exame',
            name='local_realizacao',
        ),
        migrations.CreateModel(
            name='ReceitaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('frequencia', models.CharField(blank=True, max_length=100)),
                ('duracao', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='meu_app.medicamento')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='meu_app.receita')),
            ],
            options={
                'verbose_name': 'Item de Receita',
                'verbose_name_plural': 'Itens de Receita',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='meu_app.clinica'),
        ),
        migrations.AddField(
            model_name='exame',
            name='clinica_realizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='meu_app.clinica'),
        ),
        migrations.AddField(
            model_name='medico',
            name='clinicas',
            field=models.ManyToManyField(blank=True, related_name='medicos', to='meu_app.clinica'),
        ),
    ]
