# Generated by Django 4.2.7 on 2025-08-26 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0004_clinica_medicamento_remove_exame_local_realizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='meu_app.clinica'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('medico', 'Médico'), ('paciente', 'Paciente'), ('admin', 'Administrador'), ('clinica', 'Clínica')], max_length=20),
        ),
    ]
