# Generated by Django 4.2.7 on 2025-09-02 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0009_sync_paciente_id_with_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('medico', 'Médico'), ('paciente', 'Paciente'), ('admin', 'Administrador'), ('clinica', 'Clínica'), ('secretaria', 'Secretária(o)')], max_length=20),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinicas', models.ManyToManyField(blank=True, related_name='secretarias', to='meu_app.clinica')),
                ('medicos', models.ManyToManyField(blank=True, related_name='secretarias', to='meu_app.medico')),
            ],
            options={
                'verbose_name': 'Secretária(o)',
                'verbose_name_plural': 'Secretárias(os)',
            },
        ),
    ]
