# Generated by Django 4.2.7 on 2025-10-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0012_solicitacaomedico_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='assinada',
            field=models.BooleanField(default=False),
        ),
    ]
