# Generated by Django 4.2.7 on 2025-11-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0013_receita_assinada'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/medicos/'),
        ),
        migrations.AddField(
            model_name='medico',
            name='template_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
