# Generated by Django 4.2.7 on 2025-11-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0014_medico_logo_medico_template_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitaitem',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='receitaitem',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='receitaitem',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='receitaitem',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='consulta',
            name='conduta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia_doenca',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consulta',
            name='queixa_principal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consulta',
            name='resumo_clinico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='arquivo_pdf_assinado',
            field=models.FileField(blank=True, null=True, upload_to='receitas_assinadas/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('ASSINADA', 'ASSINADA')], default='PENDENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='receitaitem',
            name='posologia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='receitaitem',
            name='quantidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receitaitem',
            name='medicamento',
            field=models.CharField(max_length=255),
        ),
    ]
