# Generated by Django 4.2.7 on 2025-11-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0015_remove_receitaitem_dose_remove_receitaitem_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='validade',
            field=models.DateField(blank=True, help_text='Data de validade da receita', null=True),
        ),
    ]
